name: newscleanarch
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  
  #State Management
  flutter_bloc: ^8.1.6
  
  #Comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.7.0

  #dateFormat
  intl: ^0.19.0

  #database
  floor: ^1.5.0

  #make request to api
  retrofit: ^4.1.0

  #hooks
  flutter_hooks: ^0.20.5

  #cached network
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  

  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.1
  floor_generator: ^1.5.0


flutter:

  
  uses-material-design: true


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
